# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "kartverket.vectortiles.sprites"
  tags:
  - "public"
spec:
  type: "documentation"
  lifecycle: "production"
  owner: "datadeling_og_distribusjon"
  system: "tjenester"
